<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3.2 (Python 3.11.4 on win32)" generated="2025-10-02T18:32:22.831151" rpa="false" schemaversion="5">
<suite id="s1" name="Home" source="c:\QAx\projects\yodapp-robot\tests\home.robot">
<test id="s1-t1" name="Deve abrir a tela principal" line="5">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2025-10-02T18:32:27.324363" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B055D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2025-10-02T18:32:31.412475" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B06950&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2025-10-02T18:32:35.509777" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B07390&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2025-10-02T18:32:39.612706" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2025-10-02T18:32:39.612706" elapsed="0.131437">No application is open</status>
</kw>
<msg time="2025-10-02T18:32:39.745142" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-10-02T18:32:39.745142" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B0DC10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<arg>http://localhost:4723</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Android Emulator</arg>
<arg>automationName=UIAutomator2</arg>
<arg>app=${EXECDIR}/app/yodapp-beta.apk</arg>
<arg>udid=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<doc>Opens a new application to the given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.19/guides/caps/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | No     | alias             |</doc>
<status status="FAIL" start="2025-10-02T18:32:23.221445" elapsed="16.525697">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B0DC10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>Yodapp</arg>
<doc>Waits until the ``text`` appears on the current page.</doc>
<status status="NOT RUN" start="2025-10-02T18:32:39.748142" elapsed="0.000000"/>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>Mobile Training</arg>
<doc>Waits until the ``text`` appears on the current page.</doc>
<status status="NOT RUN" start="2025-10-02T18:32:39.748142" elapsed="0.000000"/>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>by Papito</arg>
<doc>Waits until the ``text`` appears on the current page.</doc>
<status status="NOT RUN" start="2025-10-02T18:32:39.749141" elapsed="0.000000"/>
</kw>
<kw name="Close Application" owner="AppiumLibrary">
<doc>Closes the current application and the webdriver session.</doc>
<status status="NOT RUN" start="2025-10-02T18:32:39.749141" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2025-10-02T18:32:23.220444" elapsed="16.528697">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B0DC10&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<status status="FAIL" start="2025-10-02T18:32:22.838662" elapsed="16.911480"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Home" id="s1" pass="0" fail="1" skip="0">Home</stat>
</suite>
</statistics>
<errors>
<msg time="2025-10-02T18:32:27.324363" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B055D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2025-10-02T18:32:31.412475" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B06950&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2025-10-02T18:32:35.509777" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EDA8B07390&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2025-10-02T18:32:39.745142" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
